### ISSUE TITLE
[BUG] searching spinner only visible on first open

### ISSUE THREAD

**Issue by saithis** [bithost-gmbh/ngx-mat-select-search#153]
**Describe the bug**
When the searching input is true and I open the select dropdown multiple times, then the spinner is only visible the first time.

**To Reproduce**

1. Go to https://stackblitz.com/edit/github-raw9gr?file=src%2Fapp%2Fexamples%2F01-single-selection-example%2Fsingle-selection-example.component.html
2. Open the single selection dropdown (spinner is visible)
3. Close it
4. Open the single selection dropdown again (spinner is *not* visible)

**Expected behavior**
Spinner is visible as long as the searching input is true.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: I tried Firefox 68 and Chrome 74

**Comment by macjohnny** [comment]
thanks for reporting. this is due to the animation not being correctly run and can be fixed similar to https://github.com/bithost-gmbh/ngx-mat-select-search/issues/133 by removing the animation

**Comment by macjohnny** [comment]
this is fixed in `1.7.6`

**Comment by vipulism** [comment]
> this is fixed in `1.7.6`

this still exist in 1.7.6
however i saw #133 but not sure how to use it here. 
can you please help me here 

Thanks

**Comment by macjohnny** [comment]
@vipulism I can't seem to reproduce the issue with `1.7.6`, see https://stackblitz.com/edit/github-yhlsun?file=src/app/examples/01-single-selection-example/single-selection-example.component.html 
Please open a new issue with a concise description and the corresponding reproduction steps, so I can have a look at it.
