### ISSUE TITLE
[BUG] Input isn't added

### ISSUE THREAD

**Issue by boscharnau** [bithost-gmbh/ngx-mat-select-search#310]
I am having the issue that the input doesn't appear. I don't understand what I am missing. I have just copied the code of the example:

client.input.component.ts
````
import {
  Component,
  OnInit,
  HostListener,
  Input,
  ViewChild,
} from "@angular/core";
import { FormGroup, FormControl } from "@angular/forms";
import { MatSelect } from "@angular/material/select";
import { ActivatedRoute } from "@angular/router";
import { ReplaySubject, Subject } from "rxjs";
import { take, takeUntil } from "rxjs/operators";

export interface Bank {
  id: string;
  name: string;
}

export interface BankGroup {
  name: string;
  banks: Bank[];
}
export const BANKS: Bank[] = [
  { name: "Bank A (Switzerland)", id: "A" },
  { name: "Bank B (Switzerland)", id: "B" },
  { name: "Bank C (France)", id: "C" },
  { name: "Bank D (France)", id: "D" },
  { name: "Bank E (France)", id: "E" },
  { name: "Bank F (Italy)", id: "F" },
  { name: "Bank G (Italy)", id: "G" },
  { name: "Bank H (Italy)", id: "H" },
  { name: "Bank I (Italy)", id: "I" },
  { name: "Bank J (Italy)", id: "J" },
  { name: "Bank Kolombia (United States of America)", id: "K" },
  { name: "Bank L (Germany)", id: "L" },
  { name: "Bank M (Germany)", id: "M" },
  { name: "Bank N (Germany)", id: "N" },
  { name: "Bank O (Germany)", id: "O" },
  { name: "Bank P (Germany)", id: "P" },
  { name: "Bank Q (Germany)", id: "Q" },
  { name: "Bank R (Germany)", id: "R" },
];
@Component({
  selector: "app-client-input",
  templateUrl: "./client-input.component.html",
  styleUrls: ["./client-input.component.scss"],
})

/** list of banks */
export class ClientInputComponent implements OnInit {
  showAutocomplete = false;
  clients = [];
  clientsAll = [];
  //@Input() formProject: FormGroup;
  /** list of banks */
  protected banks: Bank[] = BANKS;

  /** control for the selected bank */
  public bankCtrl: FormControl = new FormControl();

  /** control for the MatSelect filter keyword */
  public bankFilterCtrl: FormControl = new FormControl();

  /** list of banks filtered by search keyword */
  public filteredBanks: ReplaySubject<Bank[]> = new ReplaySubject<Bank[]>(1);

  @ViewChild("singleSelect", { static: true }) singleSelect: MatSelect;

  /** Subject that emits when the component has been destroyed. */
  protected _onDestroy = new Subject<void>();

  constructor() {}

  ngOnInit() {
    // set initial selection
    this.bankCtrl.setValue(this.banks[10]);

    // load the initial bank list
    this.filteredBanks.next(this.banks.slice());

    // listen for search field value changes
    this.bankFilterCtrl.valueChanges
      .pipe(takeUntil(this._onDestroy))
      .subscribe(() => {
        this.filterBanks();
      });
  }

  ngAfterViewInit() {
    this.setInitialValue();
  }

  ngOnDestroy() {
    this._onDestroy.next();
    this._onDestroy.complete();
  }

  /**
   * Sets the initial value after the filteredBanks are loaded initially
   */
  protected setInitialValue() {
    this.filteredBanks
      .pipe(take(1), takeUntil(this._onDestroy))
      .subscribe(() => {
        // setting the compareWith property to a comparison function
        // triggers initializing the selection according to the initial value of
        // the form control (i.e. _initializeSelection())
        // this needs to be done after the filteredBanks are loaded initially
        // and after the mat-option elements are available
        this.singleSelect.compareWith = (a: Bank, b: Bank) =>
          a && b && a.id === b.id;
      });
  }

  protected filterBanks() {
    if (!this.banks) {
      return;
    }
    // get the search keyword
    let search = this.bankFilterCtrl.value;
    if (!search) {
      this.filteredBanks.next(this.banks.slice());
      return;
    } else {
      search = search.toLowerCase();
    }
    // filter the banks
    this.filteredBanks.next(
      this.banks.filter((bank) => bank.name.toLowerCase().indexOf(search) > -1)
    );
  }
  @HostListener("document:keydown.escape", ["$event"]) onKeydownHandler(
    evt: KeyboardEvent
  ) {
    this.showAutocomplete = false;
  }
}

````

client.input.component.html
````
<mat-form-field>
  <mat-select [formControl]="bankCtrl" placeholder="Bank" #singleSelect>
    <mat-option>
      <ngx-mat-select-search [formControl]="bankFilterCtrl" placeholderLabel="Search here..."></ngx-mat-select-search>
    </mat-option>
    <mat-option *ngFor="let bank of filteredBanks | async" [value]="bank">
      {{bank.name}}
    </mat-option>
  </mat-select>
</mat-form-field>
````

package.json

````
"dependencies": {
    "@alyle/ui": "^3.1.2",
    "@angular/animations": "~9.0.4",
    "@angular/cdk": "^9.1.0",
    "@angular/common": "~9.0.4",
    "@angular/compiler": "~9.0.4",
    "@angular/core": "~9.0.4",
    "@angular/forms": "~9.0.4",
    "@angular/material": "^9.1.0",
    "@angular/platform-browser": "~9.0.4",
    "@angular/platform-browser-dynamic": "~9.0.4",
    "@angular/router": "~9.0.4",
    "@swimlane/ngx-charts": "^13.0.2",
    "@types/ua-parser-js": "^0.7.33",
    "hammerjs": "^2.0.8",
    "html-to-pdfmake": "^1.2.2",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "ngx-mat-select-search": "^3.2.0",
    "ngx-quill": "^7.3.12",
    "pdf-lib": "^1.16.0",
    "pdfmake": "^0.1.65",
    "quill": "^1.3.6",
    "rxjs": "~6.5.4",
    "socket.io-client": "^2.3.0",
    "tslib": "^1.10.0",
    "ua-parser-js": "^0.7.21",
    "zone.js": "~0.10.2"
  },
````

![image](https://user-images.githubusercontent.com/71315068/113825020-c3b59f00-9780-11eb-81a2-74156c1f6cff.png)

**Comment by macjohnny** [comment]
Which browser are you using?
Can you inspect the html code in the browser and check whether the placeholder attribute of the input field is there?

**Comment by boscharnau** [comment]
I am using Google Chrome. The input field isn't there. Neither the ngx-mat-select-search tag. 

Some compatiblies issues maybe? I don't understand why the input field isn't there.

![image](https://user-images.githubusercontent.com/71315068/113821252-26586c00-977c-11eb-8a71-94b50c95de7a.png)

**Comment by avalynn-tan** [comment]
Reinstall all dependencies using `yarn install` worked for me.

**Comment by boscharnau** [comment]
It is solved.

**Comment by ajuanjojjj** [comment]
It's happening to me too, and `npm install` does not seem to fix the issue.
